/* CONTANTS GLOBAL */
export const FAILED_FETCH_LIST = 'Im Sorry Your Service Is Trouble'

/* API CONSTANTS */
export const BASE_URL = 'https://pokeapi.co/api/v2'

/* HOMEPAGE CONSTANTS */
export const HOMEPAGE_TITLE = 'POKEDEX'
export const HOMEPAGE_BUTTON_BROWSER = 'BROWSE YOUR POKEMON'
export const HOMEPAGE_BUTTON_COMPARE = 'COMPARE YOUR POKEMON'
export const HOMEPAGE_BUTTON_PREDICTION = 'PREDICTION BATTLE'
