/* CONTANTS GLOBAL */

/* HOMEPAGE CONSTANTS */
export const HOMEPAGE_TITLE = 'POKEDEX'
export const HOMEPAGE_BUTTON_BROWSER = 'BROWSE YOUR POKEMON'
export const HOMEPAGE_BUTTON_COMPARE = 'COMPARE YOUR POKEMON'
export const HOMEPAGE_BUTTON_PREDICTION = 'PREDICTION BATTLE'